### ISSUE TITLE
Allow to override element data in a configuration file

### ISSUE THREAD

**Issue by Luthaf** [chemfiles/chemfiles#75]
This is a proposal to add *configuration file* to chemfiles. These configuration files could contain two kind of data:

- element mapping: allow the user to specify that Oh is an oxygen, that C_h should be a carbon, ...
- element data: give mass, charge, radius for pseudo-elements: CH3, NH2, ALA, ... This could also be used to override pre-existing values: setting the charge for all oxygens for example.

## User interface

The configuration file should be automatically loaded from `~/.chemfilesrc` if such a file exists on OS X and Linux. On Windows, I'll have to look where to put such files.

The user could also provide a specific file to be used, changing the behaviour of Atom constructor.

## File format and syntax

I propose to use the [TOML](https://github.com/toml-lang/toml) format. There are multiple C++ implementation for this, I like the [cpptoml](https://github.com/skystrife/cpptoml) one, but I am open to other suggestions.

The file could look like this:

```toml
# Set the atomic type for the given atomic names 
[types]
O_h = "O"
"234" = "Rd"

# Override data by atom type
[atoms]
O = {charge = -1.0}
CH3 = {radius = 4.2}
```

## Code changes

To implement this, we would need to change how the atomic data are accessed to check first for anything in a configuration file.

We also need to add a C++ function to set the path to a new configuration file, and mirror this function in the C API.

---

What do you think about this proposal? Is it useful? What could be missing? 

Ping @lscalfi who is interested in this.

**Comment by lscalfi** [comment]
I was more thinking about something like this:
```[water_oxygen]
    name = "Ow"
    type = "O"
    mass = 16
    charge = -2
    radius = 1

[water_hydrogen]
    name = "Hw"
    type = "H"
    mass = 1
    charge = +1
    radius = 1.2
```
What do you think?

**Comment by Luthaf** [comment]
Using TOML allow to write table either inline as in my example, or in multiple lines as in yours. Your example is equivalent to

```toml
water_oxygen = {name = "Ow", type = "O", mass = 16, charge = -2, radius = 1}
water_hydrogen = {name = "Hw", type = "H", mass = 1, charge = +1, radius = 1.2}
```

And mine is equivalent to 

```toml
[atoms.O]
charge = -1.0

[atoms.CH3]
radius = 4.2
charge = 0
```
